### ISSUE TITLE
Require Apk file

### ISSUE THREAD

**Issue by Graveyard9988** [Dr4iv3rNope/NotSoAndroidAyuGram#2]
How can I access to latest apk of your fork?

Please help

**Comment by Dr4iv3rNope** [comment]
Since c0be04343e3b6bccde769591a6879ce3f487f8b3 you can download APK from [Github Actions tab](https://github.com/Dr4iv3rNope/NotSoAndroidAyuGram/actions)

**Comment by Graveyard9988** [comment]
Thanks a million for providing this.
